python main_visual_losslandscape.py --model Transfer_VGG_SNN --node-type LIFNode --source-dataset CALTECH101 --target-dataset NCALTECH101 --step 10 --batch-size 500 --eval --eval_checkpoint /home/hexiang/TransferLearning_For_DVS/Results_new_compare/train_TCKA_test/Transfer_VGG_SNN-NCALTECH101-10-bs_120-seed_47-DA_False-ls_0.0-lr_0.005-SNR_0-domainLoss_True-semanticLoss_True-domain_loss_coefficient1.0-semantic_loss_coefficient0.001-traindataratio_0.1-TETfirst_True-TETsecond_True/last.pth.tar --mpi --x=-1.0:1.0:51 --y=-1.0:1.0:51 --dir_type weights --xnorm filter --xignore biasbn --ynorm filter --yignore biasbn --plot --smoothing 0.0 --output /home/hexiang/TransferLearning_For_DVS/Results_new_compare/ --traindata-ratio 0.1 --num-classes 101 --device 0 --seed 47&


python main_visual_losslandscape.py --model VGG_SNN --node-type LIFNode --source-dataset CALTECH101 --target-dataset NCALTECH101 --step 10 --batch-size 500 --eval --eval_checkpoint /home/hexiang/TransferLearning_For_DVS/Results_new_compare/Baseline/VGG_SNN-NCALTECH101-10-seed_47-bs_120-DA_False-ls_0.0-lr_0.005-traindataratio_0.1-TET_first_True-TET_second_True/last.pth.tar --mpi --x=-1.0:1.0:51 --y=-1.0:1.0:51 --dir_type weights --xnorm filter --xignore biasbn --ynorm filter --yignore biasbn --plot --smoothing 0.0 --output /home/hexiang/TransferLearning_For_DVS/Results_new_compare/ --traindata-ratio 0.1 --num-classes 101 --device 7 --seed 2&


python main_visual_losslandscape.py --model Transfer_VGG_SNN --node-type LIFNode --source-dataset cifar10 --target-dataset dvsc10 --step 10 --batch-size 1000 --eval --eval_checkpoint /home/hexiang/TransferLearning_For_DVS/Results_new_compare/train_TCKA_test/Transfer_VGG_SNN-dvsc10-10-bs_120-seed_47-DA_True-ls_0.0-lr_0.005-SNR_0-domainLoss_True-semanticLoss_True-domain_loss_coefficient1.0-semantic_loss_coefficient0.5-traindataratio_0.1-TETfirst_True-TETsecond_True/last.pth.tar --mpi --x=-1.0:1.0:51 --y=-1.0:1.0:51 --dir_type weights --xnorm filter --xignore biasbn --ynorm filter --yignore biasbn --plot --DVS-DA --smoothing 0.0 --output /home/hexiang/TransferLearning_For_DVS/Results_new_compare/ --traindata-ratio 0.1 --device 2 --seed 47&


python main_visual_losslandscape.py --model VGG_SNN --node-type LIFNode --source-dataset cifar10 --target-dataset dvsc10 --step 10 --batch-size 1000 --eval --eval_checkpoint /home/hexiang/TransferLearning_For_DVS/Results_new_compare/Baseline/VGG_SNN-dvsc10-10-seed_47-bs_120-DA_True-ls_0.0-lr_0.005-traindataratio_0.1-TET_first_True-TET_second_True/last.pth.tar --mpi --x=-1.0:1.0:51 --y=-1.0:1.0:51 --dir_type weights --xnorm filter --xignore biasbn --ynorm filter --yignore biasbn --plot --DVS-DA --smoothing 0.0 --output /home/hexiang/TransferLearning_For_DVS/Results_new_compare/ --traindata-ratio 0.1 --device 3 --seed 47&